/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     2017/12/18 20:49:01                          */
/*==============================================================*/


/*==============================================================*/
/* Table: FGO_ATTRIBUTE                                         */
/*==============================================================*/
CREATE TABLE FGO_ATTRIBUTE
(
  ID   VARCHAR2(2) NOT NULL,
  NAME VARCHAR2(64)
);

COMMENT ON TABLE FGO_ATTRIBUTE IS
'属性九宫格';

COMMENT ON COLUMN FGO_ATTRIBUTE.ID IS
'id';

COMMENT ON COLUMN FGO_ATTRIBUTE.NAME IS
'名称';

ALTER TABLE FGO_ATTRIBUTE
  ADD CONSTRAINT PK_FGO_ATTRIBUTE PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_CAMP                                              */
/*==============================================================*/
CREATE TABLE FGO_CAMP
(
  ID   INTEGER NOT NULL,
  NAME VARCHAR2(32)
);

COMMENT ON TABLE FGO_CAMP IS
'阵营';

COMMENT ON COLUMN FGO_CAMP.ID IS
'id';

COMMENT ON COLUMN FGO_CAMP.NAME IS
'名称';

ALTER TABLE FGO_CAMP
  ADD CONSTRAINT PK_FGO_CAMP PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_CLASS                                             */
/*==============================================================*/
CREATE TABLE FGO_CLASS
(
  ID      INTEGER NOT NULL,
  NAME    VARCHAR2(32),
  NAME_EN VARCHAR2(32)
);

COMMENT ON TABLE FGO_CLASS IS
'阶职';

COMMENT ON COLUMN FGO_CLASS.ID IS
'id';

COMMENT ON COLUMN FGO_CLASS.NAME IS
'名称';

COMMENT ON COLUMN FGO_CLASS.NAME_EN IS
'英文名称';

ALTER TABLE FGO_CLASS
  ADD CONSTRAINT PK_FGO_CLASS PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_MATERIAL                                          */
/*==============================================================*/
CREATE TABLE FGO_MATERIAL
(
  ID          INTEGER NOT NULL,
  NAME        VARCHAR2(64),
  TYPE        INTEGER,
  BOX         INTEGER,
  DESCRIPTION VARCHAR2(512),
  LOCATION    VARCHAR2(512)
);

COMMENT ON TABLE FGO_MATERIAL IS
'材料表';

COMMENT ON COLUMN FGO_MATERIAL.ID IS
'id';

COMMENT ON COLUMN FGO_MATERIAL.NAME IS
'名称';

COMMENT ON COLUMN FGO_MATERIAL.TYPE IS
'类型';

COMMENT ON COLUMN FGO_MATERIAL.BOX IS
'箱子类型';

COMMENT ON COLUMN FGO_MATERIAL.DESCRIPTION IS
'描述';

COMMENT ON COLUMN FGO_MATERIAL.LOCATION IS
'掉落地点';

ALTER TABLE FGO_MATERIAL
  ADD CONSTRAINT PK_FGO_MATERIAL PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_NOBLE_PHANTASM_INFO                               */
/*==============================================================*/
CREATE TABLE FGO_NOBLE_PHANTASM_INFO
(
  ID          VARCHAR2(32) NOT NULL,
  DESCRIPTION VARCHAR2(256),
  STAGE1      NUMBER(6, 2),
  STAGE2      NUMBER(6, 2),
  STAGE3      NUMBER(6, 2),
  STAGE4      NUMBER(6, 2),
  STAGE5      NUMBER(6, 2),
  TYPE        INTEGER
);

COMMENT ON TABLE FGO_NOBLE_PHANTASM_INFO IS
'宝具效果';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.ID IS
'id';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.DESCRIPTION IS
'描述';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.STAGE1 IS
'STAGE1';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.STAGE2 IS
'STAGE2';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.STAGE3 IS
'STAGE3';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.STAGE4 IS
'STAGE4';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.STAGE5 IS
'STAGE5';

COMMENT ON COLUMN FGO_NOBLE_PHANTASM_INFO.TYPE IS
'类型';

ALTER TABLE FGO_NOBLE_PHANTASM_INFO
  ADD CONSTRAINT PK_FGO_NOBLE_PHANTASM_INFO PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT                                           */
/*==============================================================*/
CREATE TABLE FGO_SERVANT
(
  ID               INTEGER NOT NULL,
  NAME_ZH          VARCHAR2(64),
  NAME_EN          VARCHAR2(64),
  NAME_JP          VARCHAR2(64),
  NICKNAME         VARCHAR2(256),
  CLASS            INTEGER,
  STAR             INTEGER,
  CAMP             INTEGER,
  ATK_STAGE0       INTEGER,
  HP_STAGE0        INTEGER,
  CARDS            VARCHAR2(5),
  ATK_STAGE4       INTEGER,
  HP_STAGE4        INTEGER,
  ATK_LV90         INTEGER,
  HP_LV90          INTEGER,
  ATK_LV100        INTEGER,
  HP_LV100         INTEGER,
  ART_HIT          INTEGER,
  BUSTER_HIT       INTEGER,
  QUICK_HIT        INTEGER,
  EXTRA_HIT        INTEGER,
  CRIT             INTEGER,
  CRIT_STAR        NUMBER(5, 4),
  NP_RATE_ART      NUMBER(5, 4),
  NP_RATE_BUSTER   NUMBER(5, 4),
  NP_RATE_QUICK    NUMBER(5, 4),
  NP_RATE_EXTRA    NUMBER(5, 4),
  NP_RATE_ATTACKED NUMBER(5, 4),
  GENDER           INTEGER,
  REGION           VARCHAR2(64),
  ATTRIBUTES       VARCHAR2(64),
  PAINTER          VARCHAR2(64),
  CV               VARCHAR2(64),
  HEIGHT           INTEGER,
  WEIGHT           INTEGER,
  ORIGIN           VARCHAR2(128)
);

COMMENT ON TABLE FGO_SERVANT IS
'英灵信息';

COMMENT ON COLUMN FGO_SERVANT.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT.NAME_ZH IS
'中文名';

COMMENT ON COLUMN FGO_SERVANT.NAME_EN IS
'英文名';

COMMENT ON COLUMN FGO_SERVANT.NAME_JP IS
'日文名';

COMMENT ON COLUMN FGO_SERVANT.NICKNAME IS
'昵称';

COMMENT ON COLUMN FGO_SERVANT.CLASS IS
'阶职';

COMMENT ON COLUMN FGO_SERVANT.STAR IS
'星级';

COMMENT ON COLUMN FGO_SERVANT.CAMP IS
'阵营';

COMMENT ON COLUMN FGO_SERVANT.ATK_STAGE0 IS
'基础ATK';

COMMENT ON COLUMN FGO_SERVANT.HP_STAGE0 IS
'基础HP';

COMMENT ON COLUMN FGO_SERVANT.CARDS IS
'配卡';

COMMENT ON COLUMN FGO_SERVANT.ATK_STAGE4 IS
'灵基4阶段ATK';

COMMENT ON COLUMN FGO_SERVANT.HP_STAGE4 IS
'灵基4阶段HP';

COMMENT ON COLUMN FGO_SERVANT.ATK_LV90 IS
'90级ATK';

COMMENT ON COLUMN FGO_SERVANT.HP_LV90 IS
'90级HP';

COMMENT ON COLUMN FGO_SERVANT.ATK_LV100 IS
'100级_ATK';

COMMENT ON COLUMN FGO_SERVANT.HP_LV100 IS
'100级_HP';

COMMENT ON COLUMN FGO_SERVANT.ART_HIT IS
'art攻击次数';

COMMENT ON COLUMN FGO_SERVANT.BUSTER_HIT IS
'buster攻击次数';

COMMENT ON COLUMN FGO_SERVANT.QUICK_HIT IS
'quick攻击次数';

COMMENT ON COLUMN FGO_SERVANT.EXTRA_HIT IS
'extra攻击次数';

COMMENT ON COLUMN FGO_SERVANT.CRIT IS
'暴击权重';

COMMENT ON COLUMN FGO_SERVANT.CRIT_STAR IS
'暴击星掉落';

COMMENT ON COLUMN FGO_SERVANT.NP_RATE_ART IS
'np率art';

COMMENT ON COLUMN FGO_SERVANT.NP_RATE_BUSTER IS
'np率buster';

COMMENT ON COLUMN FGO_SERVANT.NP_RATE_QUICK IS
'np率quick';

COMMENT ON COLUMN FGO_SERVANT.NP_RATE_EXTRA IS
'np率ex';

COMMENT ON COLUMN FGO_SERVANT.NP_RATE_ATTACKED IS
'np率被攻击';

COMMENT ON COLUMN FGO_SERVANT.GENDER IS
'性别';

COMMENT ON COLUMN FGO_SERVANT.REGION IS
'地域';

COMMENT ON COLUMN FGO_SERVANT.ATTRIBUTES IS
'属性';

COMMENT ON COLUMN FGO_SERVANT.PAINTER IS
'画师';

COMMENT ON COLUMN FGO_SERVANT.CV IS
'cv';

COMMENT ON COLUMN FGO_SERVANT.HEIGHT IS
'身高';

COMMENT ON COLUMN FGO_SERVANT.WEIGHT IS
'体重';

COMMENT ON COLUMN FGO_SERVANT.ORIGIN IS
'出处';

ALTER TABLE FGO_SERVANT
  ADD CONSTRAINT PK_FGO_SERVANT PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_CLASS_SKILL                               */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_CLASS_SKILL
(
  ID         VARCHAR2(32) NOT NULL,
  SERVANT_ID INTEGER,
  NAME       VARCHAR2(32),
  "LEVEL"    VARCHAR2(8),
  INFO_ID    VARCHAR2(32),
  SID        INTEGER
);

COMMENT ON TABLE FGO_SERVANT_CLASS_SKILL IS
'阶职技能';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL.NAME IS
'名称';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL."LEVEL" IS
'固有等级';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL.INFO_ID IS
'技能描述';

COMMENT ON COLUMN FGO_SERVANT_CLASS_SKILL.SID IS
'序号';

ALTER TABLE FGO_SERVANT_CLASS_SKILL
  ADD CONSTRAINT PK_FGO_SERVANT_CLASS_SKILL PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_MATERIAL                                  */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_MATERIAL
(
  ID         VARCHAR2(32) NOT NULL,
  SERVANT_ID INTEGER,
  SID        INTEGER,
  "LEVEL"    INTEGER,
  COUNT      INTEGER,
  QP         INTEGER,
  TYPE       INTEGER
);

COMMENT ON TABLE FGO_SERVANT_MATERIAL IS
'从者素材';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.SID IS
'序号';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL."LEVEL" IS
'等级';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.COUNT IS
'数量';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.QP IS
'量子';

COMMENT ON COLUMN FGO_SERVANT_MATERIAL.TYPE IS
'类型';

ALTER TABLE FGO_SERVANT_MATERIAL
  ADD CONSTRAINT PK_FGO_SERVANT_MATERIAL PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_NOBLE_PHANTASM                            */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_NOBLE_PHANTASM
(
  ID         VARCHAR2(32) NOT NULL,
  SERVANT_ID INTEGER,
  NAME       VARCHAR2(32),
  NAME_EN    VARCHAR2(32),
  "LEVEL"    VARCHAR2(8),
  INFO_ID    VARCHAR2(32)
);

COMMENT ON TABLE FGO_SERVANT_NOBLE_PHANTASM IS
'从者宝具';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM.NAME IS
'名称';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM.NAME_EN IS
'英文名';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM."LEVEL" IS
'固有等级';

COMMENT ON COLUMN FGO_SERVANT_NOBLE_PHANTASM.INFO_ID IS
'技能效果';

ALTER TABLE FGO_SERVANT_NOBLE_PHANTASM
  ADD CONSTRAINT PK_FGO_SERVANT_NOBLE_PHANTASM PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_SKILL                                     */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_SKILL
(
  ID         VARCHAR2(32) NOT NULL,
  SERVANT_ID INTEGER,
  NAME       VARCHAR2(32),
  "LEVEL"    VARCHAR2(8),
  INFO_ID    VARCHAR2(32)
);

COMMENT ON TABLE FGO_SERVANT_SKILL IS
'从者技能';

COMMENT ON COLUMN FGO_SERVANT_SKILL.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_SKILL.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_SKILL.NAME IS
'名称';

COMMENT ON COLUMN FGO_SERVANT_SKILL."LEVEL" IS
'固有等级';

COMMENT ON COLUMN FGO_SERVANT_SKILL.INFO_ID IS
'技能效果';

ALTER TABLE FGO_SERVANT_SKILL
  ADD CONSTRAINT PK_FGO_SERVANT_SKILL PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_STORY                                     */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_STORY
(
  ID          VARCHAR2(32) NOT NULL,
  SERVANT_ID  INTEGER,
  SID         INTEGER,
  NAME        VARCHAR2(32),
  DESCRIPTION VARCHAR2(8)
);

COMMENT ON TABLE FGO_SERVANT_STORY IS
'从者故事';

COMMENT ON COLUMN FGO_SERVANT_STORY.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_STORY.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_STORY.SID IS
'序号';

COMMENT ON COLUMN FGO_SERVANT_STORY.NAME IS
'名称';

COMMENT ON COLUMN FGO_SERVANT_STORY.DESCRIPTION IS
'描述';

ALTER TABLE FGO_SERVANT_STORY
  ADD CONSTRAINT PK_FGO_SERVANT_STORY PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SERVANT_VOICE                                     */
/*==============================================================*/
CREATE TABLE FGO_SERVANT_VOICE
(
  ID          VARCHAR2(32) NOT NULL,
  SERVANT_ID  INTEGER,
  SID         INTEGER,
  NAME        VARCHAR2(32),
  DESCRIPTION VARCHAR2(8),
  TYPE        INTEGER
);

COMMENT ON TABLE FGO_SERVANT_VOICE IS
'从者语音';

COMMENT ON COLUMN FGO_SERVANT_VOICE.ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_VOICE.SERVANT_ID IS
'id';

COMMENT ON COLUMN FGO_SERVANT_VOICE.SID IS
'序号';

COMMENT ON COLUMN FGO_SERVANT_VOICE.NAME IS
'名称';

COMMENT ON COLUMN FGO_SERVANT_VOICE.DESCRIPTION IS
'描述';

COMMENT ON COLUMN FGO_SERVANT_VOICE.TYPE IS
'type';

ALTER TABLE FGO_SERVANT_VOICE
  ADD CONSTRAINT PK_FGO_SERVANT_VOICE PRIMARY KEY (ID);

/*==============================================================*/
/* Table: FGO_SKILL_INFO                                        */
/*==============================================================*/
CREATE TABLE FGO_SKILL_INFO
(
  ID          VARCHAR2(32) NOT NULL,
  DESCRIPTION VARCHAR2(256),
  VALUE       NUMBER(6, 2),
  GROWTH      NUMBER(6, 2)
);

COMMENT ON TABLE FGO_SKILL_INFO IS
'技能效果';

COMMENT ON COLUMN FGO_SKILL_INFO.ID IS
'id';

COMMENT ON COLUMN FGO_SKILL_INFO.DESCRIPTION IS
'描述';

COMMENT ON COLUMN FGO_SKILL_INFO.VALUE IS
'初始数值';

COMMENT ON COLUMN FGO_SKILL_INFO.GROWTH IS
'成长';

ALTER TABLE FGO_SKILL_INFO
  ADD CONSTRAINT PK_FGO_SKILL_INFO PRIMARY KEY (ID);

ALTER TABLE FGO_NOBLE_PHANTASM_INFO
  ADD CONSTRAINT FK_FGO_NOBL_REFERENCE_FGO_SERV FOREIGN KEY (ID)
REFERENCES FGO_SERVANT_NOBLE_PHANTASM (ID);

ALTER TABLE FGO_SERVANT_CLASS_SKILL
  ADD CONSTRAINT FK_SERVANT_CLASS FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SERVANT_MATERIAL
  ADD CONSTRAINT FK_SERVANT_MATERIAL FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SERVANT_NOBLE_PHANTASM
  ADD CONSTRAINT FK_SERVANT_NOBLE_PHANTASM FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SERVANT_SKILL
  ADD CONSTRAINT FK_SERVANT_SKILL FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SERVANT_STORY
  ADD CONSTRAINT FK_SERVANT_STORY FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SERVANT_VOICE
  ADD CONSTRAINT FK_SERVANT_VOICE FOREIGN KEY (SERVANT_ID)
REFERENCES FGO_SERVANT (ID);

ALTER TABLE FGO_SKILL_INFO
  ADD CONSTRAINT FK_FGO_SKIL_REFERENCE_FGO_SERV FOREIGN KEY (ID)
REFERENCES FGO_SERVANT_SKILL (ID);

