spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/fgowiki
        username: fgowiki
        password: 123456
        druid:
           #最大活跃数
          maxActive: 20
          #初始化数量
          initialSize: 1
          #最大连接等待超时时间
          maxWait: 60000
          #打开PSCache，并且指定每个连接PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
          #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 1 from dual
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
          filters: stat, wall , slf4j

    jpa:
        hibernate:
            naming:
            ## jpa命名策略
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
    redis:
        database: 0
        host: 127.0.0.1
        password: fgowiki456
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0
    output:
      ansi:
        enabled: DETECT
server:
  port: 9999

